export default function getData() {
  const parkingMap = [
    { type: "Parking", no: 1, place: 0 },
    { type: "Parking", no: 2, place: 1 },
    { type: "Parking", no: 3, place: 2 },
    { type: "Parking", no: 4, place: 3 },
    { type: "Parking", no: 5, place: 4 },
    { type: "Parking", no: 6, place: 5 },
    { type: "Parking", no: 7, place: 6 },
    { type: "Parking", no: 8, place: 7 },
    { type: "Parking", no: 9, place: 8 },
    { type: "Parking", no: 10, place: 9 },
    { type: "Parking", no: 11, place: 10 },
    { type: "Parking", no: 12, place: 11 },
    { type: "Parking", no: 13, place: 12 },
    { type: "Parking", no: 14, place: 13 },
    { type: "Parking", no: 15, place: 14 },
    { type: "Parking", no: 16, place: 15 },

    { type: "path", place: 16 },
    { type: "path", place: 17 },
    { type: "path", place: 18 },
    { type: "path", place: 19 },
    { type: "path", place: 20 },
    { type: "path", place: 21 },
    { type: "path", place: 22 },
    { type: "path", place: 23 },
    { type: "path", place: 24 },
    { type: "path", place: 25 },
    { type: "path", place: 26 },
    { type: "path", place: 27 },
    { type: "path", place: 28 },
    { type: "path", place: 29 },
    { type: "path", place: 30 },
    { type: "path", place: 31 },
    { type: "path", place: 32 },
    { type: "path", place: 33 },

    { type: "Parking", no: 17, place: 34 },
    { type: "Parking", no: 18, place: 35 },
    { type: "Parking", no: 19, place: 36 },
    { type: "Parking", no: 20, place: 37 },
    { type: "Parking", no: 21, place: 38 },
    { type: "Parking", no: 22, place: 39 },
    { type: "Parking", no: 23, place: 40 },
    { type: "Parking", no: 24, place: 41 },
    { type: "Parking", no: 25, place: 42 },
    { type: "Parking", no: 26, place: 43 },
    { type: "Parking", no: 27, place: 44 },

    { type: "path", place: 45 },
    { type: "path", place: 46 },
    { type: "path", place: 47 },
    { type: "path", place: 48 },
    { type: "path", place: 49 },

    { type: "Parking", no: 28, place: 50 },
    { type: "Parking", no: 29, place: 51 },
    { type: "Parking", no: 30, place: 52 },
    { type: "Parking", no: 31, place: 53 },
    { type: "Parking", no: 32, place: 54 },
    { type: "Parking", no: 33, place: 55 },
    { type: "Parking", no: 34, place: 56 },
    { type: "Parking", no: 35, place: 57 },
    { type: "Parking", no: 36, place: 58 },
    { type: "Parking", no: 37, place: 59 },
    { type: "Parking", no: 38, place: 60 },

    { type: "path", place: 61 },
    { type: "path", place: 62 },
    { type: "path", place: 63 },
    { type: "path", place: 64 },
    { type: "path", place: 65 },
    { type: "path", place: 66 },
    { type: "path", place: 67 },
    { type: "path", place: 68 },
    { type: "path", place: 69 },
    { type: "path", place: 70 },
    { type: "path", place: 71 },
    { type: "path", place: 72 },
    { type: "path", place: 73 },
    { type: "path", place: 74 },
    { type: "path", place: 75 },
    { type: "path", place: 76 },
    { type: "path", place: 77 },
    { type: "path", place: 78 },
    { type: "path", place: 79 },

    { type: "Parking", no: 39, place: 80 },
    { type: "Parking", no: 40, place: 81 },
    { type: "Parking", no: 41, place: 82 },
    { type: "Parking", no: 42, place: 83 },
    { type: "Parking", no: 43, place: 84 },
    { type: "Parking", no: 44, place: 85 },
    { type: "Parking", no: 45, place: 86 },
    { type: "Parking", no: 46, place: 87 },
    { type: "Parking", no: 47, place: 88 },
    { type: "Parking", no: 48, place: 89 },
    { type: "Parking", no: 49, place: 90 },
    { type: "Parking", no: 50, place: 91 },
    { type: "Parking", no: 51, place: 92 },
    { type: "Parking", no: 52, place: 93 },
    { type: "Parking", no: 53, place: 94 },
    { type: "Parking", no: 54, place: 95 },
  ];
  return { parkingMap };
}
